version: '3.7'
services:
    service_1:
        container_name: "service_1"
        image: pranaywara/service_1
        build: ./service_1
        ports:
            - '5000:5000'
        environment:
            DATABASE_URI: ${DATABASE_URI}
        env_file: .env
        
    service_2:
        container_name: "service_2"
        image: pranaywara/service_2
        build: ./service_2

    service_3:
        container_name: "service_3"
        image: pranaywara/service_3
        build: ./service_3

    service_4:
        container_name: "service_4"
        image: pranaywara/service_4
        build: ./service_4
