version: '3.7'
services:
  
    service_1:
        container_name: "service_1"
        image: pranaywara/service_1
        build: ./service_1
        ports:
        - target: 5000
          published: 5000
          protocol: tcp
        environment:
            DATABASE_URI: 
        deploy:
            replicas: 2
              
    service_2:
        container_name: "service_2"
        image: pranaywara/service_2
        build: ./service_2
        deploy:
            replicas: 2


    service_3:
        container_name: "service_3"
        image: pranaywara/service_3
        build: ./service_3
        deploy:
            replicas: 2


    service_4:
        container_name: "service_4"
        image: pranaywara/service_4
        build: ./service_4
        deploy:
            replicas: 2