pipeline{
        agent any
        environment{
            DATABASE_URI = credentials("DATABASE_URI")
            DOCKERHUB_CREDENTIALS = credentials("DOCKERHUB_CREDENTIALS")
        }
        stages{
            stage('Test'){
                steps {
                    sh 'bash scripts/test.sh'
                }
            }
            stage('Build'){
                steps {
                    sh 'bash scripts/build.sh'
                }
            }
            stage('Ansible') {
                steps {
                    sh "cd ansible && ansible-playbook -i inventory.yaml ansible-playbook.yaml"
                }
            }
            stage('Configure'){
                steps {
                    sh 'bash scripts/configure.sh'
                }
            }    
            stage('Deploy'){
                steps {
                    sh 'bash scripts/deploy.sh'
                }
            }         
        }
    }