pipeline{
    agent any
    enviroment{
        DATABASE_URI = credentials("DATABASE_URI")
        DOCKERHUB_CREDENTIALS= credentials('DOCKERHUB_CREDENTIALS')
    }
    stages{
        stage('Debug'){
            steps{
                sh "docker login -u ${DOCKERHUB_CREDENTIALS_USR} -p ${DOCKERHUB_CREDENTIALS_PSW}"
            }
        }
    }
}
