---
# tasks file for nginx
- name: 'install nginx with apt'
  become: true
  apt:
    pkg:
    - nginx
    state: latest
    update_cache: true

- name: Copy nginx file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  register: nginx_conf

- name: restart is needed
  service: 
    name: nginx
    state: restarted
  when: nginx_conf.changed == true

- name: debug config
  debug:
    msg: "{{ nginx_conf }}"