---
# tasks file for nginx
- name: Install NGINX
  apt:
    name: nginx
    update_cache: True

- name: Template nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  register: ngin_info

# - name: Restart NGINX
#   service:
#     name: nginx
#     state: restarted
#   when: nginx_info.changed == true