---
# tasks file for nginx
  - name: Install NGINX
    become: True
    apt:
      name: nginx
      state: latest
      update_cache: True

  - name: Start NGINX Service
    become: True
    service:
      name: nginx
      state: started

  - name: Add nginx conf
    become: True
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    notify: 'reload nginx'