---
# tasks file for docker
- name: 'Docker dependencies'
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - lsb-release
      - python3
      - python3-pip
    state: latest
    update_cache: true
- name: 'Docker apt key'
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: 'Docker repo'
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release|lower }} stable
    state: present
- name: 'Install Docker engine'
  become: true
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: true
- name: 'Add user to Dockergroup'
  become: true 
  user: 
    name: jenkins
    groups: docker
    append: true 
- name: 'Install Docker SDK'
  become: true
  pip:
    name: docker-py