- hosts: nginx
  become: true
  tasks:
  - name: Install NGINX
    apt:
      name: nginx
      state: latest
      update_cache: true

  - name: Start NGINX Service
    service:
      name: nginx
      state: started
  - name: Add nginx conf
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: Debugg msg
    debug:
      msg: "Hello from nginx"

  - name: Restart nginx
    service: 
      name: nginx
      state: restarted