all: 
  hosts: 
    load-balancer:
  children:
    managers:
      hosts:
        swarm-manager:
    workers:
      hosts:
        swarm-worker:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'