---
# tasks file for join-swarm
- name: Join Swarm
  become: true
  docker_swarm:
    state: join
    advertise_addr: 
    join_token: "{{ hostvars['swarm-manager'].swarm_info.swarm_facts.JoinTokens.Worker }}"
    remote_addrs: [ swarm-manager ]