---
# tasks file for initialise-swarm
  - name: Initialise Swarm
    become: true
    docker_swarm:
      state: present
    register: swarm_info

  - name: debug swarm
    debug:
      msg: "{{ swarm_info }}"